language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - python manage.py test
after_success:
  - coveralls

