# Generated by Django 3.2.2 on 2021-05-18 00:07

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('inserted', 'Inserted'), ('consumed', 'Consumed')], default=False, max_length=8)),
                ('data', models.JSONField()),
                ('steps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), blank=True, default=list, size=None)),
            ],
        ),
    ]
